-- Seed normalized thiền đường from danh sách trụ trì
-- Idempotent by slug
BEGIN;

-- 1. Thiền Viện Linh Sơn
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('04094309-ae10-5847-80dc-616d6c3e3944', 'thien-vien-linh-son-thich-minh-hien', 'Thiền Viện Linh Sơn', 'Thích Minh Hiển', 'HT', 'Trụ trì', 'Chứng minh', 'TANG', 'TRUNG', 'VN', 'Lâm Đồng', 'Xã Bảo Lâm 3, tỉnh Lâm Đồng', '0908557867', '0908557867', 1, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = '04094309-ae10-5847-80dc-616d6c3e3944';
INSERT INTO courses (id, title, type, recurrence, day_start, day_end, weekday, schedule_text, center_id, sort_order) VALUES ('0e2c0925-ff8c-52a7-9883-47fe2d69827c', 'Khóa tu thiền thất', 'REGULAR', 'SELF_PRACTICE', NULL, NULL, NULL, 'Tự tu', '04094309-ae10-5847-80dc-616d6c3e3944', 1);
INSERT INTO courses (id, title, type, recurrence, day_start, day_end, weekday, schedule_text, center_id, sort_order) VALUES ('d6aa52fd-a0d1-5394-9184-4c6188abbbe8', 'Khóa tu mùa đông', 'WINTER', 'YEARLY', NULL, NULL, NULL, 'Khóa tu mùa đông', '04094309-ae10-5847-80dc-616d6c3e3944', 2);
INSERT INTO courses (id, title, type, recurrence, start_date, end_date, schedule_text, center_id, sort_order) VALUES ('ea0bfdd3-b05e-5772-a978-75522db4c686', 'An cư', 'AN_CU', 'YEARLY', '2026-04-08'::date, '2026-07-04'::date, '8/4-4/7', '04094309-ae10-5847-80dc-616d6c3e3944', 3);

-- 2. Tịnh Xá Ngọc Hòa
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('6e08e2af-224e-54d2-894c-d41b78b81931', 'tinh-xa-ngoc-hoa-thich-giac-diep', 'Tịnh Xá Ngọc Hòa', 'Thích Giác Điệp', 'HT', 'Trụ trì', 'Chứng minh', 'TANG', 'NAM', 'VN', 'Cần Thơ', 'Khu vực Thới Hưng, phường Thới Long, TP. Cần Thơ', '0907883578', '0907883578', 2, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = '6e08e2af-224e-54d2-894c-d41b78b81931';
INSERT INTO courses (id, title, type, recurrence, day_start, day_end, weekday, schedule_text, center_id, sort_order) VALUES ('7169904f-1fd8-5565-be57-4a3db7edab88', 'Khóa tu thiền thất', 'REGULAR', 'MONTHLY_RANGE', 10, 16, NULL, '10-16', '6e08e2af-224e-54d2-894c-d41b78b81931', 1);
INSERT INTO courses (id, title, type, recurrence, start_date, end_date, schedule_text, center_id, sort_order) VALUES ('a390b697-5806-541b-9b3e-c3bc215ce86c', 'An cư', 'AN_CU', 'YEARLY', '2026-04-11'::date, '2026-07-11'::date, '11/4-11/7', '6e08e2af-224e-54d2-894c-d41b78b81931', 2);

-- 3. Chùa Liên Hoa
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('1a459595-395a-59e5-918a-668c5a518d05', 'chua-lien-hoa-thich-duy-tran', 'Chùa Liên Hoa', 'Thích Duy Trần', 'HT', 'Trụ trì', NULL, 'TANG', 'NAM', 'VN', 'TP.HCM', '236/31/4 Thái Phiên, phường Bình Thới, TP.HCM', '0903924772', '0903924772', 3, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = '1a459595-395a-59e5-918a-668c5a518d05';
INSERT INTO courses (id, title, type, recurrence, day_start, day_end, weekday, schedule_text, center_id, sort_order) VALUES ('4c0c05bd-dc25-582d-b36c-de09425cc867', 'Khóa tu thiền thất', 'REGULAR', 'WEEKLY', NULL, NULL, 0, 'CN/Tuần', '1a459595-395a-59e5-918a-668c5a518d05', 1);
INSERT INTO courses (id, title, type, recurrence, start_date, end_date, schedule_text, center_id, sort_order) VALUES ('413f3328-b33e-51b6-9657-e53668067305', 'An cư', 'AN_CU', 'YEARLY', '2026-04-13'::date, '2026-07-13'::date, '13/4-13/7', '1a459595-395a-59e5-918a-668c5a518d05', 2);

-- 4. Thiền Đường Liễu Quán 1
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('b9f7def7-8733-58cd-a515-11951618f7e9', 'thien-duong-lieu-quan-1-thich-hue-minh', 'Thiền Đường Liễu Quán 1', 'Thích Huệ Minh', 'HT', 'Trụ trì', 'Phó', 'TANG', 'NAM', 'VN', 'TP.HCM', 'Thôn Phước Thành, phường Tân Hải, TP.HCM', '0908400155', '0908400155', 4, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = 'b9f7def7-8733-58cd-a515-11951618f7e9';
INSERT INTO courses (id, title, type, recurrence, day_start, day_end, weekday, schedule_text, center_id, sort_order) VALUES ('1c757bbd-bbc4-5755-89cd-e3af999e7a05', 'Khóa tu thiền thất', 'REGULAR', 'MONTHLY_RANGE', 1, 7, NULL, '01-07', 'b9f7def7-8733-58cd-a515-11951618f7e9', 1);

-- 5. Chùa Thiên Trì
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('d7246326-8c35-56f2-9310-dc3276b5ccb3', 'chua-thien-tri-thich-minh-thien', 'Chùa Thiên Trì', 'Thích Minh Thiên', 'HT', 'Viện chủ', 'TBTK', 'TANG', 'NAM', 'VN', 'TP.HCM', 'Xã Bình Hưng, TP.HCM', '0908400155', '0908400155', 5, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = 'd7246326-8c35-56f2-9310-dc3276b5ccb3';
INSERT INTO courses (id, title, type, recurrence, day_start, day_end, weekday, schedule_text, center_id, sort_order) VALUES ('3f9f9796-958c-5105-9188-73680575bf91', 'Khóa tu thiền thất', 'REGULAR', 'MONTHLY_RANGE', 14, 20, NULL, '14-20', 'd7246326-8c35-56f2-9310-dc3276b5ccb3', 1);

-- 6. Chùa Huyền Trang
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('e752a813-7240-5c5c-939b-44d33441ed5d', 'chua-huyen-trang-thich-thien-chieu', 'Chùa Huyền Trang', 'Thích Thiện Chiêu', 'HT', 'Trưởng Ban QT', 'Phó', 'TANG', 'NAM', 'VN', 'TP.HCM', '2056/39 Huỳnh Tấn Phát, xã Nhà Bè, TP.HCM', '0918666239', '0918666239', 6, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = 'e752a813-7240-5c5c-939b-44d33441ed5d';

-- 7. Chùa Tam Bảo
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('b10b7f1e-a606-58bd-ab2f-469698519ae3', 'chua-tam-bao-thich-thien-tai', 'Chùa Tam Bảo', 'Thích Thiện Tài', 'HT', 'Trụ trì', NULL, 'TANG', 'NAM', 'VN', 'Đồng Tháp', 'Ấp Tân Thuận, xã Tân Nhuận Đông, Đồng Tháp', '0908535369', '0908535369', 7, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = 'b10b7f1e-a606-58bd-ab2f-469698519ae3';
INSERT INTO courses (id, title, type, recurrence, day_start, day_end, weekday, schedule_text, center_id, sort_order) VALUES ('12d9a53d-be15-5f44-b9cf-e5e3c1ba8c96', 'Khóa tu mùa đông', 'WINTER', 'YEARLY', NULL, NULL, NULL, 'Khóa tu mùa đông', 'b10b7f1e-a606-58bd-ab2f-469698519ae3', 1);

-- 8. Chùa Phật Quang
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('4e5aa4b4-20ac-5e1c-9736-4410af5bdcff', 'chua-phat-quang-thich-minh-hoa', 'Chùa Phật Quang', 'Thích Minh Hòa', 'HT', 'Trụ trì', NULL, 'TANG', 'NAM', 'VN', 'Đồng Tháp', 'Ấp Tân An, xã Tân Phú Trung, Đồng Tháp', '0764666841', '0764666841', 8, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = '4e5aa4b4-20ac-5e1c-9736-4410af5bdcff';

-- 9. Chùa Phước Điền
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('c6d123fc-341b-5113-8746-02bd643884bc', 'chua-phuoc-dien-thich-minh-ngoc', 'Chùa Phước Điền', 'Thích Minh Ngọc', 'HT', 'Trụ trì', NULL, 'TANG', 'NAM', 'VN', 'An Giang', '646A đường Vòng Núi Sam, phường Núi Sam, An Giang', '0773133777', '0773133777', 9, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = 'c6d123fc-341b-5113-8746-02bd643884bc';

-- 10. Tu Viện Thanh Long
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('75fd6b4e-f51b-58c2-87f8-8ba898c3dd80', 'tu-vien-thanh-long-thich-nhut-tay', 'Tu Viện Thanh Long', 'Thích Nhựt Tây', 'HT', NULL, NULL, 'TANG', 'NUOC_NGOAI', 'US', NULL, 'Santa Ana, CA, USA', '001(714)6229307', '001(714)6229307', 10, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = '75fd6b4e-f51b-58c2-87f8-8ba898c3dd80';

-- 11. Từ Ân Thiền Đường
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('040b2c17-5429-5221-ac71-43425e77c3c6', 'tu-an-thien-duong-thich-minh-tho', 'Từ Ân Thiền Đường', 'Thích Minh Thọ', 'HT', 'Trụ trì', NULL, 'TANG', 'NAM', 'VN', 'TP.HCM', 'Khu phố Phước Thành, phường Tân Hòa, TP.HCM', '0984314739', '0984314739', 11, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = '040b2c17-5429-5221-ac71-43425e77c3c6';

-- 12. Thiền Tự Quy Sơn
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('d056f6c8-f609-51f2-9660-14b9ad51406c', 'thien-tu-quy-son-thich-thien-pham', 'Thiền Tự Quy Sơn', 'Thích Thiện Phẩm', 'TT', NULL, 'TTLL', 'TANG', 'NAM', 'VN', 'Đồng Nai', 'Ấp Tân Bình, phường Bửu Hòa, TP. Biên Hòa, Đồng Nai', '0984315181', '0984315181', 12, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = 'd056f6c8-f609-51f2-9660-14b9ad51406c';
INSERT INTO courses (id, title, type, recurrence, day_start, day_end, weekday, schedule_text, center_id, sort_order) VALUES ('71d2121b-8290-5e87-a782-ad6f39166b2e', 'Khóa tu thiền thất', 'REGULAR', 'MONTHLY_RANGE', 16, 22, NULL, '16-22', 'd056f6c8-f609-51f2-9660-14b9ad51406c', 1);
INSERT INTO courses (id, title, type, recurrence, day_start, day_end, weekday, schedule_text, center_id, sort_order) VALUES ('1aaec8e3-5e92-5094-8ae6-9478eaf9c11c', 'Khóa tu mùa xuân', 'SPRING', 'YEARLY', NULL, NULL, NULL, 'Khóa tu mùa xuân', 'd056f6c8-f609-51f2-9660-14b9ad51406c', 2);
INSERT INTO courses (id, title, type, recurrence, start_date, end_date, schedule_text, center_id, sort_order) VALUES ('508dff64-4e32-5e60-b17d-2d8cda9984b8', 'An cư', 'AN_CU', 'YEARLY', '2026-04-16'::date, '2026-07-11'::date, '16/4-11/7', 'd056f6c8-f609-51f2-9660-14b9ad51406c', 3);

-- 13. Tổ Đình Long Thiền
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('83c20059-e0ad-5db5-9d9a-7bb21e55ec36', 'to-dinh-long-thien-thich-tac-quang', 'Tổ Đình Long Thiền', 'Thích Tắc Quang', 'TT', NULL, 'TTLL', 'TANG', 'NAM', 'VN', 'An Giang', 'Ấp Núi Két, phường Thới Sơn, An Giang', '0918575774', '0918575774', 13, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = '83c20059-e0ad-5db5-9d9a-7bb21e55ec36';
INSERT INTO courses (id, title, type, recurrence, day_start, day_end, weekday, schedule_text, center_id, sort_order) VALUES ('dbc005eb-588e-5a5b-9830-a94ab61e504c', 'Khóa tu thiền thất', 'REGULAR', 'MONTHLY_RANGE', 21, 27, NULL, '21-27', '83c20059-e0ad-5db5-9d9a-7bb21e55ec36', 1);

-- 14. Chùa Thới Hưng
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('67254744-65e5-5adc-99da-60fcdc28120d', 'chua-thoi-hung-thich-nhuan-thuan', 'Chùa Thới Hưng', 'Thích Nhuận Thuận', 'TT', 'Trụ trì', NULL, 'TANG', 'NAM', 'VN', 'TP.HCM', 'B15/20, xã Bình Hưng, TP.HCM', '0976207061', '0976207061', 14, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = '67254744-65e5-5adc-99da-60fcdc28120d';

-- 15. Chùa Thiên Trì
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('5fd318a2-8a97-57fd-9c80-6b98e386481c', 'chua-thien-tri-thich-trung-due', 'Chùa Thiên Trì', 'Thích Trung Duệ', 'TT', 'Trụ trì', NULL, 'TANG', 'NAM', 'VN', 'TP.HCM', '524/28 Nguyễn Đình Chiểu, phường Bàn Cờ, TP.HCM', '0908901842', '0908901842', 15, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = '5fd318a2-8a97-57fd-9c80-6b98e386481c';
INSERT INTO courses (id, title, type, recurrence, day_start, day_end, weekday, schedule_text, center_id, sort_order) VALUES ('cf7097ab-816d-51e2-b9de-9e9605f99e24', 'Khóa tu thiền thất', 'REGULAR', 'MONTHLY_RANGE', 6, 12, NULL, '06-12', '5fd318a2-8a97-57fd-9c80-6b98e386481c', 1);

-- 16. Chùa Huê Quang
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('17d94835-d47c-5608-b669-a16868d368bd', 'chua-hue-quang-thich-thien-chon', 'Chùa Huê Quang', 'Thích Thiện Chơn', 'TT', 'Trụ trì', NULL, 'TANG', 'NUOC_NGOAI', 'US', NULL, '14851 Wilson St, Midway City, CA 92655, Hoa Kỳ', '001(714)6229307', '001(714)6229307', 16, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = '17d94835-d47c-5608-b669-a16868d368bd';

-- 17. Chùa Duy Pháp
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('63d1d7db-0e7e-5099-94ae-5e62fec78bc1', 'chua-duy-phap-thich-hue-tri', 'Chùa Duy Pháp', 'Thích Huệ Trí', 'TT', 'Trụ trì', NULL, 'TANG', 'NAM', 'VN', 'TP.HCM', '362/46 Nguyễn Đình Chiểu, phường Bàn Cờ, TP.HCM', '0918251975', '0918251975', 17, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = '63d1d7db-0e7e-5099-94ae-5e62fec78bc1';
INSERT INTO courses (id, title, type, recurrence, day_start, day_end, weekday, schedule_text, center_id, sort_order) VALUES ('3771b840-98c8-5ab4-87a9-a87e49e09af0', 'Khóa tu thiền thất', 'REGULAR', 'MONTHLY_RANGE', 6, 12, NULL, '06-12', '63d1d7db-0e7e-5099-94ae-5e62fec78bc1', 1);
INSERT INTO courses (id, title, type, recurrence, start_date, end_date, schedule_text, center_id, sort_order) VALUES ('4e93c9b3-fcb7-53a5-a034-68718d4c26c8', 'An cư', 'AN_CU', 'YEARLY', '2026-04-16'::date, '2026-07-16'::date, '16/4-16/7', '63d1d7db-0e7e-5099-94ae-5e62fec78bc1', 2);

-- 18. Chùa Long Sơn
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('5a232f0d-af9e-5ae5-ae10-67d8fdfd200c', 'chua-long-son-thich-quang-phuc', 'Chùa Long Sơn', 'Thích Quảng Phúc', 'TT', 'Trụ trì', 'Nhiếp ảnh', 'TANG', 'NAM', 'VN', 'An Giang', 'Ấp Núi Két, phường Thới Sơn, An Giang', '0985116649', '0985116649', 18, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = '5a232f0d-af9e-5ae5-ae10-67d8fdfd200c';
INSERT INTO courses (id, title, type, recurrence, start_date, end_date, schedule_text, center_id, sort_order) VALUES ('036e4ee0-81c2-568b-be5d-aed977043511', 'An cư', 'AN_CU', 'YEARLY', '2026-04-10'::date, '2026-07-10'::date, '10/4-10/7', '5a232f0d-af9e-5ae5-ae10-67d8fdfd200c', 1);

-- 19. Chùa An Phước
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('a3d90a99-38b2-5f9f-8ede-e1ee5c6e4c8c', 'chua-an-phuoc-thich-le-dao', 'Chùa An Phước', 'Thích Lệ Đạo', 'TT', 'Trụ trì', NULL, 'TANG', 'NAM', 'VN', 'An Giang', 'Ấp An Ninh, xã Hội An, An Giang', '0919726186', '0919726186', 19, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = 'a3d90a99-38b2-5f9f-8ede-e1ee5c6e4c8c';
INSERT INTO courses (id, title, type, recurrence, day_start, day_end, weekday, schedule_text, center_id, sort_order) VALUES ('4fe863c0-755d-5466-9c05-798db5e14ea0', 'Khóa tu thiền thất', 'REGULAR', 'MONTHLY_RANGE', 3, 9, NULL, '03-09', 'a3d90a99-38b2-5f9f-8ede-e1ee5c6e4c8c', 1);

-- 20. Chùa Long Đức
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('c30cd246-da80-5b67-b18d-652863b3de94', 'chua-long-duc-thich-thien-quang', 'Chùa Long Đức', 'Thích Thiện Quang', 'ĐĐ', 'Trụ trì', NULL, 'TANG', 'TRUNG', 'VN', 'Lâm Đồng', 'Xã Trà Tân, tỉnh Lâm Đồng', '0909079425', '0909079425', 20, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = 'c30cd246-da80-5b67-b18d-652863b3de94';

-- 21. Chùa Phật Quang
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('b1c42562-b390-5bed-9bef-8a6d7293dd2b', 'chua-phat-quang-thich-tinh-tri', 'Chùa Phật Quang', 'Thích Tịnh Trí', 'ĐĐ', 'Trụ trì', NULL, 'TANG', 'NAM', 'VN', 'Cần Thơ', 'Ấp Trường Thuận, xã Trường Long, TP. Cần Thơ', '0388565642', '0388565642', 21, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = 'b1c42562-b390-5bed-9bef-8a6d7293dd2b';
INSERT INTO courses (id, title, type, recurrence, day_start, day_end, weekday, schedule_text, center_id, sort_order) VALUES ('542af4fd-7c82-5808-9be6-58f2e70b89f0', 'Khóa tu thiền thất', 'REGULAR', 'WEEKLY', NULL, NULL, 0, 'CN', 'b1c42562-b390-5bed-9bef-8a6d7293dd2b', 1);

-- 22. Chùa Sơn Hải
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('c52a0456-68de-56ed-a00b-70673663092c', 'chua-son-hai-thich-duc-son', 'Chùa Sơn Hải', 'Thích Đức Sơn', 'ĐĐ', 'Trụ trì', NULL, 'TANG', 'TRUNG', 'VN', 'Khánh Hòa', 'Thôn Ninh Đảo, xã Đại Lãnh, Khánh Hòa', '0365488810', '0365488810', 22, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = 'c52a0456-68de-56ed-a00b-70673663092c';
INSERT INTO courses (id, title, type, recurrence, day_start, day_end, weekday, schedule_text, center_id, sort_order) VALUES ('84ed301a-0242-536c-82e3-88bbb3d4fea0', 'Khóa tu thiền thất', 'REGULAR', 'MONTHLY_RANGE', 28, 4, NULL, '28-04', 'c52a0456-68de-56ed-a00b-70673663092c', 1);
INSERT INTO courses (id, title, type, recurrence, start_date, end_date, schedule_text, center_id, sort_order) VALUES ('cce2a90b-f8c0-5086-a6f2-156b0168fbe3', 'An cư', 'AN_CU', 'YEARLY', '2026-04-06'::date, '2026-07-06'::date, '6/4-6/7', 'c52a0456-68de-56ed-a00b-70673663092c', 2);

-- 23. Chùa Phước Quang
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('44ab8cbe-4e37-5e9c-a71b-e51f8803a322', 'chua-phuoc-quang-thich-nhuan-nguyen', 'Chùa Phước Quang', 'Thích Nhuận Nguyên', 'ĐĐ', 'Trụ trì', NULL, 'TANG', 'NAM', 'VN', 'Bà Rịa - Vũng Tàu', 'KP Tân Phú, phường Phú Mỹ, TP.HCM (BR-VT cũ)', '0932653153', '0932653153', 23, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = '44ab8cbe-4e37-5e9c-a71b-e51f8803a322';

-- 24. Chùa Phú Thọ
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('2f16b013-558b-5b83-a075-8b50077b21c9', 'chua-phu-tho-thich-giac-tien', 'Chùa Phú Thọ', 'Thích Giác Tiến', 'ĐĐ', 'Trụ trì', NULL, 'TANG', 'TRUNG', 'VN', 'Lâm Đồng', 'Thôn 3, xã Hàm Liêm, tỉnh Lâm Đồng', '0845950943', '0845950943', 24, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = '2f16b013-558b-5b83-a075-8b50077b21c9';

-- 25. Chùa Huyền Trang
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('adda31d3-aeeb-5953-8e07-6cfe13d0e9fc', 'chua-huyen-trang-thich-minh-phu', 'Chùa Huyền Trang', 'Thích Minh Phú', 'ĐĐ', NULL, NULL, 'TANG', 'NAM', 'VN', 'TP.HCM', '2025/39 đường Huỳnh Tấn Phát, phường Nhà Bè, TP.HCM', '0886997243', '0886997243', 25, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = 'adda31d3-aeeb-5953-8e07-6cfe13d0e9fc';

-- 26. Chùa Liên Hoa
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('25843d94-29c6-548b-a4ac-7c94182dd782', 'chua-lien-hoa-thich-phap-hien', 'Chùa Liên Hoa', 'Thích Pháp Hiện', 'ĐĐ', NULL, NULL, 'TANG', 'NAM', 'VN', 'TP.HCM', '2025/39 đường Huỳnh Tấn Phát, phường Nhà Bè, TP.HCM', '0936623761', '0936623761', 26, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = '25843d94-29c6-548b-a4ac-7c94182dd782';

-- 27. Chùa Thiền Ân
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('4144379b-5492-5de5-be31-317ec3569457', 'chua-thien-an-thich-phap-nhan', 'Chùa Thiền Ân', 'Thích Pháp Nhẫn', 'ĐĐ', NULL, NULL, 'TANG', 'NAM', 'VN', 'TP.HCM', 'Số 58 đường Ông Ích Khiêm / Ông Niệm, xã Bình Hưng, TP.HCM', '001(281)8577047', '001(281)8577047', 27, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = '4144379b-5492-5de5-be31-317ec3569457';

-- 28. Chùa Phật Đà
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('5b499dc6-4f17-58dd-b725-0c7776df5fca', 'chua-phat-da-thich-nhuan-nghia', 'Chùa Phật Đà', 'Thích Nhuận Nghĩa', 'ĐĐ', NULL, NULL, 'TANG', 'NUOC_NGOAI', 'US', NULL, 'Houston, Texas, USA', '001(281)8577047', '001(281)8577047', 28, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = '5b499dc6-4f17-58dd-b725-0c7776df5fca';

-- 29. Chùa Tân Phước
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('775f04e4-c6a6-5ebf-a330-08faa3778dbf', 'chua-tan-phuoc-thich-quang-binh', 'Chùa Tân Phước', 'Thích Quang Bình', 'ĐĐ', 'Trụ trì', NULL, 'TANG', 'NAM', 'VN', 'TP.HCM', '362/46 Nguyễn Đình Chiểu, phường Bàn Cờ, TP.HCM', '0778061727', '0778061727', 29, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = '775f04e4-c6a6-5ebf-a330-08faa3778dbf';

-- 30. Chùa Phước Lộc
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('003bfa78-a898-5774-92e9-c867154917fd', 'chua-phuoc-loc-thich-nhuan-binh', 'Chùa Phước Lộc', 'Thích Nhuận Bình', 'ĐĐ', NULL, NULL, 'TANG', 'NAM', 'VN', 'Vĩnh Long', 'Ấp Tân Hòa, xã Tân Xuân, tỉnh Vĩnh Long', '0938422772', '0938422772', 30, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = '003bfa78-a898-5774-92e9-c867154917fd';

-- 31. Linh Quang Thiền Tự
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('130ac824-33c3-5283-b95f-f884caab5c40', 'linh-quang-thien-tu-thich-hue-dao', 'Linh Quang Thiền Tự', 'Thích Huệ Đạo', 'ĐĐ', NULL, NULL, 'TANG', 'NAM', 'VN', 'Tây Ninh', '126 Tôn Thất Tùng, Tân Biên, Tây Ninh', '0938299996', '0938299996', 31, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = '130ac824-33c3-5283-b95f-f884caab5c40';

-- 32. Chùa Thượng
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('f58b0b66-94ab-5917-8c91-8f72a32e9b8c', 'chua-thuong-thich-thanh-an', 'Chùa Thượng', 'Thích Thanh An', 'ĐĐ', 'Trụ trì', NULL, 'TANG', 'BAC', 'VN', 'Bắc Ninh', 'Khu phố Ninh, phường Kinh Bắc, tỉnh Bắc Ninh', '0974986486', '0974986486', 32, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = 'f58b0b66-94ab-5917-8c91-8f72a32e9b8c';

-- 33. Thiền Viện Linh Sơn
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('6c1b28a8-8f96-5d96-8c5a-05f2d7a48630', 'thien-vien-linh-son-thich-nhuan-quy', 'Thiền Viện Linh Sơn', 'Thích Nhuận Quy', 'ĐĐ', NULL, NULL, 'TANG', 'BAC', 'VN', 'Thái Nguyên', 'Phường Sông Công, tỉnh Thái Nguyên', '0967746777', '0967746777', 33, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = '6c1b28a8-8f96-5d96-8c5a-05f2d7a48630';

-- 36. Chùa Pháp Thành
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('0fe82666-44f2-5862-af76-90b5c745cbf2', 'chua-phap-thanh-t-nu-an-huong', 'Chùa Pháp Thành', 'T Nữ An Hương', 'NS', 'Viện chủ', NULL, 'NI', 'TRUNG', 'VN', 'Lâm Đồng', 'Xã Bảo Lâm 3, tỉnh Lâm Đồng', '0913676009', '0913676009', 36, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = '0fe82666-44f2-5862-af76-90b5c745cbf2';

-- 37. Chùa Quang Nhân
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('e78560e2-7e7a-5eaf-b617-828d5ea1f542', 'chua-quang-nhan-t-nu-dam-tri', 'Chùa Quang Nhân', 'T Nữ Đàm Trì', 'NS', 'Trụ trì', NULL, 'NI', 'NAM', 'VN', 'TP.HCM', '192/32/4 Phan Văn Chí, P.4, Q.3, TP.HCM', '0969328681', '0969328681', 37, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = 'e78560e2-7e7a-5eaf-b617-828d5ea1f542';

-- 38. Chùa Liên Hương
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('576a363a-15aa-5811-aca3-7902205c0d42', 'chua-lien-huong-hue-y', 'Chùa Liên Hương', 'Huệ Ý', 'SC', 'Trụ trì', NULL, 'NI', 'BAC', 'VN', 'Hà Nội', 'Quận Cầu Giấy, Hà Nội', '0386466874', '0386466874', 38, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = '576a363a-15aa-5811-aca3-7902205c0d42';

-- 39. Tịnh Thất Phước Nguyên
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('4ed86adf-615f-5c4c-95d5-0b38117f61a8', 'tinh-that-phuoc-nguyen-an-dao', 'Tịnh Thất Phước Nguyên', 'An Đảo', 'SC', 'Trụ trì', NULL, 'NI', 'NAM', 'VN', 'Đồng Tháp', 'Ấp Tân Hòa 2, xã Phú Hữu, tỉnh Đồng Tháp', '0825720729', '0825720729', 39, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = '4ed86adf-615f-5c4c-95d5-0b38117f61a8';

-- 40. Chùa Liên Hoa
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('1c61ee74-1b45-545d-a70c-0f7fa284e043', 'chua-lien-hoa-t-nu-buu-nhat', 'Chùa Liên Hoa', 'T Nữ Bửu Nhật', 'SC', 'Trụ trì', NULL, 'NI', 'NAM', 'VN', 'TP.HCM', 'Đường Lê Thị Đỏ, xã Bà Điểm, TP.HCM', '0906780196', '0906780196', 40, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = '1c61ee74-1b45-545d-a70c-0f7fa284e043';

-- 41. Thiền Viện Duy Lực
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('2a397e2d-98e1-5729-9eca-a57c16867c21', 'thien-vien-duy-luc-t-nu-phap-ngan', 'Thiền Viện Duy Lực', 'T Nữ Pháp Ngân', 'SC', NULL, NULL, 'NI', 'NAM', 'VN', 'TP.HCM', 'Số 58 đường Ông Niệm, xã Bình Hưng, TP.HCM', '0907274882', '0907274882', 41, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = '2a397e2d-98e1-5729-9eca-a57c16867c21';
INSERT INTO courses (id, title, type, recurrence, day_start, day_end, weekday, schedule_text, center_id, sort_order) VALUES ('c4381d32-bca6-59d5-b7ba-b15726fe4531', 'Khóa tu mùa đông', 'WINTER', 'YEARLY', NULL, NULL, NULL, 'Khóa tu mùa đông', '2a397e2d-98e1-5729-9eca-a57c16867c21', 1);

-- 42. Chùa Pháp Thành
INSERT INTO centers (id, slug, temple_name, abbot_name, abbot_rank, abbot_title, org_role, gender_section, region, country_code, province, address, phone, abbot_phone, sort_order, is_published, gallery_images) VALUES ('7804a816-70ba-5958-9d30-8512f3acaf4a', 'chua-phap-thanh-t-nu-an-huu', 'Chùa Pháp Thành', 'T Nữ An Hữu', 'SC', 'Trụ trì', NULL, 'NI', 'NAM', 'VN', 'Đồng Nai', 'Tổ 8, ấp 4, phường Long Hưng, TP. Đồng Nai', '0836357624', '0836357624', 42, true, '[]'::jsonb) ON CONFLICT (slug) DO UPDATE SET temple_name=EXCLUDED.temple_name, abbot_name=EXCLUDED.abbot_name, abbot_rank=EXCLUDED.abbot_rank, abbot_title=EXCLUDED.abbot_title, org_role=EXCLUDED.org_role, gender_section=EXCLUDED.gender_section, region=EXCLUDED.region, country_code=EXCLUDED.country_code, province=EXCLUDED.province, address=EXCLUDED.address, phone=EXCLUDED.phone, abbot_phone=EXCLUDED.abbot_phone, sort_order=EXCLUDED.sort_order;
DELETE FROM courses WHERE center_id = '7804a816-70ba-5958-9d30-8512f3acaf4a';

COMMIT;
