#!/usr/bin/env python3
"""Restore Vietnamese diacritics for ASCII MP3 display titles (filenames unchanged)."""

from __future__ import annotations

import re
from pathlib import Path

# lowercase ASCII → Vietnamese (longest first)
PHRASES: list[tuple[str, str]] = [
    ("dai tong lam", "Đại Tòng Lâm"),
    ("chua phap thanh", "Chùa Pháp Thanh"),
    ("phap thanh", "Pháp Thanh"),
    ("chua hung phuoc", "Chùa Hưng Phước"),
    ("hung phuoc", "Hưng Phước"),
    ("chua tam bao", "Chùa Tam Bảo"),
    ("tam bao", "Tam Bảo"),
    ("chua tu an", "Chùa Từ Ân"),
    ("tu an", "Từ Ân"),
    ("long nguyen", "Long Nguyên"),
    ("phu lam", "Phú Lâm"),
    ("vinh gia", "Vĩnh Gia"),
    ("quy son", "Quy Sơn"),
    ("huong nghiem", "Hương Nghiêm"),
    ("lang nghiem", "Lăng Nghiêm"),
    ("lnghiem", "Lăng Nghiêm"),
    ("hoa ky", "Hoa Kỳ"),
    ("to su thien", "Tổ Sư Thiền"),
    ("su phu", "Sư Phụ"),
    ("hoa thuong", "Hòa Thượng"),
    ("tinh do", "Tịnh Độ"),
    ("thien that", "thiền thất"),
    ("thien tong", "Thiền Tông"),
    ("tin tu tam", "Tín Tự Tâm"),
    ("duy luc", "Duy Lực"),
    ("co duy tam", "cô Duy Tâm"),
    ("duy tam", "Duy Tâm"),
    ("phat thich ca", "Phật Thích Ca"),
    ("thich ca", "Thích Ca"),
    ("khang hy", "Khang Hỷ"),
    ("khai thi", "khai thị"),
    ("tham thien", "tham thiền"),
    ("tu thien", "tu thiền"),
    ("tham thoai dau", "tham thoại đầu"),
    ("thoai dau", "thoại đầu"),
    ("tham thoai", "tham thoại"),
    ("cau thoai", "câu thoại"),
    ("kien tanh", "kiến tánh"),
    ("minh tam", "minh tâm"),
    ("cong an", "công án"),
    ("nghi tinh", "nghi tình"),
    ("chon nghi", "chơn nghi"),
    ("khoi nghi", "khởi nghi"),
    ("tu do tu tai", "tự do tự tại"),
    ("tu do", "tự do"),
    ("tu tai", "tự tại"),
    ("ban lai dien muc", "bản lai diện mục"),
    ("bon lai", "bổn lai"),
    ("ban lai", "bản lai"),
    ("dien muc", "diện mục"),
    ("phien nao", "phiền não"),
    ("gioi dinh hue", "giới định tuệ"),
    ("gioi luat", "giới luật"),
    ("phat giao", "Phật giáo"),
    ("niem phat", "niệm Phật"),
    ("tong chi", "tông chỉ"),
    ("bat nhi", "bất nhị"),
    ("doi dai", "đối đãi"),
    ("tap khi", "tập khí"),
    ("nhan nghi", "nhân nghi"),
    ("qua ngo", "quả ngộ"),
    ("nhat thiet", "nhất thiết"),
    ("co ban", "cơ bản"),
    ("thuc hanh", "thực hành"),
    ("anh sang", "ánh sáng"),
    ("anh huong", "ảnh hưởng"),
    ("khong gian", "không gian"),
    ("thoi gian", "thời gian"),
    ("tinh trang", "tình trạng"),
    ("dia phuong", "địa phương"),
    ("thay doi", "thay đổi"),
    ("dung muc", "đúng mức"),
    ("tam quan trong", "tầm quan trọng"),
    ("quan trong", "quan trọng"),
    ("cu hanh", "cử hành"),
    ("loi ich", "lợi ích"),
    ("ich loi", "ích lợi"),
    ("dong nghia", "đồng nghĩa"),
    ("giai thich", "giải thích"),
    ("truong hop", "trường hợp"),
    ("thong bao", "thông báo"),
    ("tiep dan", "tiếp dẫn"),
    ("ban y", "bản ý"),
    ("ban tay", "bàn tay"),
    ("chi quan", "chỉ quán"),
    ("da toa", "đả tọa"),
    ("mo trang day nuoc", "mò trăng đáy nước"),
    ("mo trang", "mò trăng"),
    ("day nuoc", "đáy nước"),
    ("chang roi", "chăng rồi"),
    ("thi sao", "thì sao"),
    ("nhu the nao", "như thế nào"),
    ("the nao", "thế nào"),
    ("nhu the", "như thế"),
    ("tai sao", "tại sao"),
    ("vi sao", "vì sao"),
    ("lam sao", "làm sao"),
    ("ra sao", "ra sao"),
    ("bay gio", "bây giờ"),
    ("kinh xin", "kính xin"),
    ("xin khai thi", "xin khai thị"),
    ("xin khai", "xin khai"),
    ("chung con", "chúng con"),
    ("cho con", "cho con"),
    ("mot minh", "một mình"),
    ("1 minh", "1 mình"),
    ("o chua", "ở chùa"),
    ("ve chua", "về chùa"),
    ("xa hoi", "xã hội"),
    ("phuc vu", "phục vụ"),
    ("lam chu", "làm chủ"),
    ("chinh minh", "chính mình"),
    ("tu si", "tu sĩ"),
    ("bon phan", "bổn phận"),
    ("hat chau ma ni", "hạt châu ma ni"),
    ("hat chau", "hạt châu"),
    ("tuy sac", "tùy sắc"),
    ("vo tru", "vô trụ"),
    ("lam goc", "làm gốc"),
    ("chanh phap", "chánh pháp"),
    ("nhap dinh", "nhập định"),
    ("troi sao", "trời sao"),
    ("giai thoat", "giải thoát"),
    ("thap dia bo tat", "thập địa Bồ Tát"),
    ("bo tat", "Bồ Tát"),
    ("thap dia", "thập địa"),
    ("lo mo", "lờ mờ"),
    ("thien mon", "thiền môn"),
    ("giao mon", "giáo môn"),
    ("vo thuong su", "vô thượng sư"),
    ("vo thuong", "vô thượng"),
    ("a nau da la", "a-nậu-đà-la"),
    ("tam nieu", "tâm niệm"),
    ("tam bo de", "tâm bồ đề"),
    ("bo de", "bồ đề"),
    ("thuong thay", "thường thấy"),
    ("loi minh", "lỗi mình"),
    ("loi nguoi", "lỗi người"),
    ("nen tu", "nên tu"),
    ("tron bon", "tròn bổn"),
    ("yen vui", "yên vui"),
    ("co phai", "có phải"),
    ("co duoc", "có được"),
    ("duoc coi", "được coi"),
    ("phai chang", "phải chăng"),
    ("khong co", "không có"),
    ("khi nao", "khi nào"),
    ("moi dut", "mới dứt"),
    ("dut duoc", "dứt được"),
    ("dut tap", "dứt tập"),
    ("cung khap", "cùng khắp"),
    ("chua kien", "chưa kiến"),
    ("lo chet", "lo chết"),
    ("chon tam", "chọn tâm"),
    ("gom gioi", "gồm giới"),
    ("giang tanh", "giảng tánh"),
    ("luc tham", "lúc tham"),
    ("an man", "ăn mặn"),
    ("co toi", "có tội"),
    ("goi y", "gợi ý"),
    ("chuyen thien", "chuyển thiền"),
    ("su that", "sự thật"),
    ("da that", "dạ thất"),
    ("du thien that", "dự thiền thất"),
    ("du thien", "dự thiền"),
    ("thang sau", "tháng sau"),
    ("nam 1988", "năm 1988"),
    ("(cop cho)", "(cóp cho)"),
    ("trinh ngay", "trình ngày"),
    ("di canada", "đi Canada"),
    ("co di", "có đi"),
    ("niet ban", "niết bàn"),
    ("khong giai", "không giải"),
    ("cac thu", "các thứ"),
    ("tu chung", "tu chứng"),
    ("chi co", "chỉ có"),
    ("chu phat", "chư Phật"),
    ("tuc a", "tức a"),
    ("thac mac", "thắc mắc"),
    ("xin su phu", "xin Sư Phụ"),
    ("thua su phu", "thưa Sư Phụ"),
    ("kinh thua", "kính thưa"),
    ("phat to", "Phật Tổ"),
    ("to su", "Tổ Sư"),
    ("thien gia", "thiền giả"),
    ("cu si", "cư sĩ"),
    ("tang gia", "Tăng già"),
    ("dai chung", "đại chúng"),
    ("tung kinh", "tụng kinh"),
    ("cha me", "cha mẹ"),
    ("sanh tu", "sanh tử"),
    ("quy cu", "quy củ"),
    ("tat ca", "tất cả"),
    ("bo oc", "bộ óc"),
    ("thanh tinh", "thanh tịnh"),
    ("nhuc dau", "nhức đầu"),
    ("kinh dien", "kinh điển"),
    ("nhac nho", "nhắc nhở"),
    ("ty kheo", "tỳ kheo"),
    ("bai ke", "bài kệ"),
    ("lot vao", "lọt vào"),
    ("day du", "đầy đủ"),
    ("qua doi", "qua đời"),
    ("cai do", "cái đó"),
    ("cai thay", "cái thấy"),
    ("tho hien", "thô hiện"),
    ("hien len", "hiện lên"),
    ("tu bot", "tu bớt"),
    ("khoi hoi", "khỏi hỏi"),
    ("cung duoc", "cũng được"),
    ("rat kho", "rất khổ"),
    ("bi danh", "bí danh"),
    ("huong bang", "hương bảng"),
    ("dang tu", "đang tu"),
    ("49 ngay", "49 ngày"),
    ("phat dang tu", "Phật đang tu"),
    ("huong cong", "hưởng công"),
    ("tap huong", "tập hưởng"),
    ("lai qua", "lại quả"),
    ("tu dau", "từ đâu"),
    ("dau xin", "đầu xin"),
    ("sao xin", "sao xin"),
    ("con xin", "con xin"),
    ("con tu", "con tu"),
    ("con tham", "con tham"),
    ("tu xin", "tu xin"),
    ("tham xin", "tham xin"),
    ("day cho", "dạy cho"),
    ("qua tham", "quả tham"),
    ("vua tham", "vừa tham"),
    ("sao con", "sao con"),
    ("trong kinh", "trong kinh"),
    ("giang tanh thay", "giảng tánh thấy"),
    ("thay trong", "thấy trong"),
    ("cho thay", "cho thấy"),
    ("nhin thay", "nhìn thấy"),
    ("khong thay", "không thấy"),
    ("co thay", "có thấy"),
    ("moi thay", "mới thấy"),
    ("deu thay", "đều thấy"),
    ("con thay", "con thấy"),
    ("lai thay", "lại thấy"),
]

# Extra phrases from AI + curated Tổ Sư Thiền glossary
_EXTRA_PATH = Path(__file__).with_name("vn_title_phrases_thien.json")
if _EXTRA_PATH.exists():
    import json as _json
    _extra = _json.loads(_EXTRA_PATH.read_text(encoding="utf-8"))
    PHRASES.extend((k, v) for k, v in _extra.items())

# Unambiguous single words only (no conflicting duplicates)
SAFE_WORDS: dict[str, str] = {
    "khong": "không",
    "duoc": "được",
    "nguoi": "người",
    "phai": "phải",
    "nhung": "những",
    "chung": "chúng",
    "nhieu": "nhiều",
    "truoc": "trước",
    "thuc": "thực",
    "hanh": "hành",
    "phat": "Phật",
    "phap": "pháp",
    "thien": "thiền",
    "niem": "niệm",
    "giang": "giảng",
    "hieu": "hiểu",
    "biet": "biết",
    "nghia": "nghĩa",
    "viec": "việc",
    "dieu": "điều",
    "ngay": "ngày",
    "thang": "tháng",
    "nam": "năm",
    "benh": "bệnh",
    "chet": "chết",
    "muon": "muốn",
    "can": "cần",
    "nen": "nên",
    "neu": "nếu",
    "hoac": "hoặc",
    "va": "và",
    "voi": "với",
    "cua": "của",
    "cho": "cho",
    "nay": "này",
    "vay": "vậy",
    "roi": "rồi",
    "da": "đã",
    "se": "sẽ",
    "dang": "đang",
    "van": "vẫn",
    "rat": "rất",
    "hon": "hơn",
    "nhat": "nhất",
    "moi": "mới",
    "het": "hết",
    "deu": "đều",
    "cac": "các",
    "mot": "một",
    "khac": "khác",
    "nhau": "nhau",
    "rieng": "riêng",
    "minh": "mình",
    "ngai": "ngài",
    "thua": "thưa",
    "xin": "xin",
    "hoi": "hỏi",
    "dap": "đáp",
    "thinh": "thỉnh",
    "trinh": "trình",
    "thuyet": "thuyết",
    "luan": "luận",
    "cau": "câu",
    "loi": "lời",
    "tieng": "tiếng",
    "nghe": "nghe",
    "nhin": "nhìn",
    # "thay" omitted: "thay đổi" vs "thấy" — use phrases
    "tim": "tìm",
    "gap": "gặp",
    "den": "đến",
    "ve": "về",
    "di": "đi",
    "ra": "ra",
    "vao": "vào",
    "len": "lên",
    "xuong": "xuống",
    "sau": "sau",
    "tren": "trên",
    "duoi": "dưới",
    "trong": "trong",
    "ngoai": "ngoài",
    "giua": "giữa",
    "gan": "gần",
    "xa": "xa",
    "ben": "bên",
    "cach": "cách",
    "luc": "lúc",
    "khi": "khi",
    "lan": "lần",
    "luon": "luôn",
    "suot": "suốt",
    "buon": "buồn",
    "kho": "khổ",
    "vui": "vui",
    "yen": "yên",
    "hy": "hỷ",
    "san": "sân",
    "si": "si",
    "tham": "tham",
    "nghi": "nghi",
    "ngo": "ngộ",
    "tinh": "tịnh",
    "dinh": "định",
    "hue": "tuệ",
    "tue": "tuệ",
    "gioi": "giới",
    "luat": "luật",
    "nghiep": "nghiệp",
    "duyen": "duyên",
    "nhan": "nhân",
    "duc": "đức",
    "phuoc": "phước",
    "ac": "ác",
    "dao": "đạo",
    "tong": "tông",
    "mon": "môn",
    "giao": "giáo",
    "hoc": "học",
    "tu": "tu",
    "xuat": "xuất",
    "gia": "gia",
    "su": "sư",
    "to": "tổ",
    "phu": "phụ",
    "thuong": "thượng",
    "ha": "hạ",
    "trung": "trung",
    "dai": "đại",
    "tieu": "tiểu",
    "bat": "bất",
    "vo": "vô",
    "huu": "hữu",
    "co": "có",
    "la": "là",
    "bi": "bị",
    "de": "để",
    "ma": "mà",
    "thi": "thì",
    "vi": "vì",
    "gi": "gì",
    "sao": "sao",
    "nao": "nào",
    "ai": "ai",
    "chi": "chỉ",
    "cung": "cùng",
    "hay": "hay",
    "o": "ở",
    "tai": "tại",
    "the": "thế",
    "nhu": "như",
    "ay": "ấy",
    "it": "ít",
    "thieu": "thiếu",
    "nua": "nữa",
    "xong": "xong",
    "dung": "đúng",
    "sai": "sai",
    "that": "thật",
    "giong": "giống",
    "ngoi": "ngồi",
    "giu": "giữ",
    "bo": "bỏ",
    "tao": "tạo",
    "pha": "phá",
    "lay": "lấy",
    "dua": "đưa",
    "mang": "mang",
    "chiu": "chịu",
    "giup": "giúp",
    "cuu": "cứu",
    "ghet": "ghét",
    "yeu": "yêu",
    "khoe": "khỏe",
    "met": "mệt",
    "ngheo": "nghèo",
    "nuoc": "nước",
    "nui": "núi",
    "meo": "mèo",
    "thit": "thịt",
    "com": "cơm",
    "ruou": "rượu",
    "uong": "uống",
    "ngu": "ngủ",
    "thuoc": "thuốc",
    "sinh": "sinh",
    "sanh": "sanh",
    "nuoi": "nuôi",
    "mua": "mua",
    "tram": "trăm",
    "ngan": "ngàn",
    "toan": "toàn",
    "vinh": "vĩnh",
    "von": "vốn",
    "xac": "xác",
    "buong": "buông",
    "khap": "khắp",
    "mong": "mong",
    "nguon": "nguồn",
    "quay": "quay",
    "tron": "tròn",
    "tuan": "tuần",
    "chat": "chất",
    "cuoc": "cuộc",
    "goc": "gốc",
    "khuyen": "khuyến",
    "lanh": "lành",
    "oan": "oan",
    "suy": "suy",
    "xay": "xảy",
    "xet": "xét",
    "chac": "chắc",
    "dep": "đẹp",
    "ket": "kết",
    "lich": "lịch",
    "luu": "lưu",
    "gom": "gồm",
    "guong": "gương",
    "uoc": "ước",
    "vuot": "vượt",
    "lam": "làm",
    "noi": "nói",
    "con": "con",
    "cha": "cha",
    "em": "em",
    "ba": "ba",
    "hai": "hai",
    "toi": "tôi",
    "ban": "bản",
    "y": "ý",
    "tri": "trí",
    "tam": "tâm",
    "than": "thân",
    "mat": "mắt",
    "long": "lòng",
    "chuyen": "chuyện",
    "giai": "giải",
    "thich": "thích",
    "quan": "quán",
    "nhap": "nhập",
    "muc": "mục",
    "phan": "phần",
    "so": "số",
    "kinh": "kinh",
    "khai": "khai",
    "bao": "bảo",
    "ung": "ứng",
    "ro": "rõ",
    "cang": "càng",
    "tot": "tốt",
    "xau": "xấu",
    "thong": "thông",
    "hinh": "hình",
    "ao": "ảo",
    "huyen": "huyền",
    "tanh": "tánh",
    "kien": "kiến",
    "thoai": "thoại",
    "thac": "thắc",
    "mac": "mắc",
    "phien": "phiền",
    "kiep": "kiếp",
    "sieu": "siêu",
    "thoat": "thoát",
    "diet": "diệt",
    "chap": "chấp",
    "vong": "vọng",
    "tuong": "tưởng",
    "chanh": "chánh",
    "dut": "dứt",
    "bot": "bớt",
    "khoi": "khỏi",
    "hien": "hiện",
    "cai": "cái",
    "vua": "vua",
    "danh": "danh",
    "huong": "hướng",
    "bang": "bảng",
    "coi": "coi",
    "theo": "theo",
    "lo": "lo",
    "qua": "qua",
    "tin": "tin",
    "me": "mẹ",
    "an": "an",
    "man": "mặn",
    "chua": "chưa",
    "thay": "thấy",  # safe now: "thay đổi" protected by placeholder
    "tuc": "tức",
    "ma": "mà",
}


def _title_case_vn(src_span: str, vn: str) -> str:
    if not src_span or not vn:
        return vn
    if src_span[0].isupper():
        return vn[0].upper() + vn[1:]
    return vn


def restore_diacritics(text: str) -> str:
    if not text:
        return text
    out = re.sub(r"\s+", " ", text).strip()

    # Protect phrase replacements from later overlapping phrase/word passes.
    placeholders: list[str] = []

    def protect(vn: str) -> str:
        placeholders.append(vn)
        return f"\x00PH{len(placeholders) - 1}\x00"

    for ascii_p, vn_p in sorted(PHRASES, key=lambda x: len(x[0]), reverse=True):
        lower = out.lower()
        start = 0
        parts: list[str] = []
        while True:
            idx = lower.find(ascii_p, start)
            if idx < 0:
                parts.append(out[start:])
                break
            before_ok = idx == 0 or not out[idx - 1].isalpha()
            end = idx + len(ascii_p)
            after_ok = end >= len(out) or not out[end].isalpha()
            if before_ok and after_ok:
                parts.append(out[start:idx])
                parts.append(protect(_title_case_vn(out[idx:end], vn_p)))
                start = end
            else:
                parts.append(out[start : idx + 1])
                start = idx + 1
        out = "".join(parts)

    def repl(m: re.Match[str]) -> str:
        w = m.group(0)
        if "\x00" in w:
            return w
        if any(ord(c) > 127 for c in w):
            return w
        if m.start() > 0 and out[m.start() - 1] == "-":
            return w
        mapped = SAFE_WORDS.get(w.lower())
        if not mapped:
            return w
        if w[0].isupper():
            return mapped[0].upper() + mapped[1:]
        return mapped

    out = re.sub(r"[A-Za-zÀ-ỹĐđ\x00]+", repl, out)
    for i, vn in enumerate(placeholders):
        out = out.replace(f"\x00PH{i}\x00", vn)
    return out



def title_from_stem(stem: str) -> str:
    base = re.sub(r"\s+", " ", stem.replace("_", " ")).strip()
    return restore_diacritics(base)
